language: node_js
node_js:
  _ "stable"
services:
  - postgresql
install:
  - npm install
before_script:
  - chmod 0777 ./node_modules/.bin/mocha
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coveralls
